name: test
on: push
jobs:
  log-date:
    runs-on: ubuntu-latest
    steps:
      - name: logdate asampedro
        run: date
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: node node-version
        run : node --version



